version: '3.3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  mongo:
    ports:
      - '27017:27017'
    container_name: demo-mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo